fix: format YAML workflow for consistency and readability

diff --git a/.github/workflows/check-dependencies.yaml b/.github/workflows/check-dependencies.yaml
--- a/.github/workflows/check-dependencies.yaml
+++ b/.github/workflows/check-dependencies.yaml
@@ -13,10 +13,10 @@ name: Check 3rd party dependencies
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-#    paths:
-#    - "Cargo.lock"
+  #    paths:
+  #    - "Cargo.lock"
   workflow_call:
   workflow_dispatch:
 
@@ -31,27 +31,27 @@ jobs:
     env:
       DASH_SUMMARY: "DEPENDENCIES.txt"
     steps:
-    - uses: actions/checkout@v4
-    - name: "Check 3rd party license compatibility"
-      id: "run-checks"
-      run: |
-        if bash .github/scripts/check-3rd-party-licenses.sh
-        then
-          echo "checks-failed=0" >> $GITHUB_OUTPUT
-          echo "License information of 3rd party dependencies has been vetted successfully." >> $GITHUB_STEP_SUMMARY
-        else
-          echo "checks-failed=1" >> $GITHUB_OUTPUT
-          echo "License information of some 3rd party dependencies could not be vetted successfully." >> $GITHUB_STEP_SUMMARY
-          echo "A DEPENDENCIES file containing the vetted information has been attached to this workflow run." >> $GITHUB_STEP_SUMMARY
-        fi
-    - name: Upload DEPENDENCIES file
-      if: ${{ steps.run-checks.outputs.checks-failed == '1' }}
-      uses: actions/upload-artifact@v4
-      with:
-        name: 3rd-party-dependencies
-        path: ${{ env.DASH_SUMMARY }}
-    - name: "Determine exit code"
-      env:
-        EXIT_CODE: ${{ steps.run-checks.outputs.checks-failed }}
-      run: |
-        exit $EXIT_CODE
+      - uses: actions/checkout@v4
+      - name: "Check 3rd party license compatibility"
+        id: "run-checks"
+        run: |
+          if bash .github/scripts/check-3rd-party-licenses.sh
+          then
+            echo "checks-failed=0" >> $GITHUB_OUTPUT
+            echo "License information of 3rd party dependencies has been vetted successfully." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "checks-failed=1" >> $GITHUB_OUTPUT
+            echo "License information of some 3rd party dependencies could not be vetted successfully." >> $GITHUB_STEP_SUMMARY
+            echo "A DEPENDENCIES file containing the vetted information has been attached to this workflow run." >> $GITHUB_STEP_SUMMARY
+          fi
+      - name: Upload DEPENDENCIES file
+        if: ${{ steps.run-checks.outputs.checks-failed == '1' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: 3rd-party-dependencies
+          path: ${{ env.DASH_SUMMARY }}
+      - name: "Determine exit code"
+        env:
+          EXIT_CODE: ${{ steps.run-checks.outputs.checks-failed }}
+        run: |
+          exit $EXIT_CODE
