add pre commit and reformat files
take over of https://github.com/eclipse-opensovd/opensovd/

* add python python-formatter
* add yaml formatter
* add end of line check

Signed-off-by: Alexander Mohr <alexander.m.mohr@mercedes-benz.com>

diff --git a/.github/workflows/requirements-tracing.yml b/.github/workflows/requirements-tracing.yml
--- a/.github/workflows/requirements-tracing.yml
+++ b/.github/workflows/requirements-tracing.yml
@@ -25,7 +25,7 @@ jobs:
       tracing-report-url: ${{ steps.upload-tracing-report.artifact-url }}
     steps:
       - uses: actions/checkout@v4
-# [impl->req~main.tracing.programmatically~1]]
+        # [impl->req~main.tracing.programmatically~1]]
       - name: Run OpenFastTrace
         id: run-oft
         uses: itsallcode/openfasttrace-github-action@v0
@@ -41,12 +41,12 @@ jobs:
         with:
           name: tracing-report-html
           path: ${{ env.TRACING_REPORT_FILE_NAME }}
-# TODO once requirements are traceable, enforce it with the exit code
-#      - name: "Determine exit code"
-#        run: |
-#          exit ${{ steps.run-oft.outputs.oft-exit-code }}
-# allow failing requirements tracing pipeline for now
-# display the error code instead
+          # TODO once requirements are traceable, enforce it with the exit code
+          #      - name: "Determine exit code"
+          #        run: |
+          #          exit ${{ steps.run-oft.outputs.oft-exit-code }}
+          # allow failing requirements tracing pipeline for now
+          # display the error code instead
       - name: "Output exit code"
         run: |
           echo ${{ steps.run-oft.outputs.oft-exit-code }}
